var amuse_TERMS = {
  "version": "4",
  "edition": "1",
  "date": "04 Oct 2014",
  "objects": {
    "terms": {
      "$terms_normal_location": [
        "Art Gallery",
        "Art Gallery (entrance)",
        "Back Staircase First Floor",
        "Back Staircase Ground Floor",
        "Back Staircase Second Floor",
        "Burnley Room",
        "Cantilever Staircase",
        "Chapel",
        "Collectors Room",
        "Craft Museum",
        "Dec Arts Room",
        "Family Dining Room",
        "Great Hall",
        "Green Drawing Room",
        "Housekeepers Room",
        "Jacobean Staircase",
        "Kitchen",
        "Long Gallery",
        "Long Gallery Bedroom III",
        "Long Gallery Bedroom IV",
        "Long Gallery Bedroom V",
        "Long Gallery Bedroom VI",
        "Massey Gallery",
        "Military Room",
        "Natural History Gallery",
        "North Gallery",
        "North Tower (ground floor)",
        "Red Drawing Room",
        "Servants Hall",
        "Service Passage",
        "Shop Passage",
        "South Tower Bedroom",
        "Towneley Room",
        "Welcome Display",
        "on loan",
        "store"
      ],
      "$terms_current_location": [
        "Art Gallery",
        "Art Gallery (entrance)",
        "Back Staircase First Floor",
        "Back Staircase Ground Floor",
        "Back Staircase Second Floor",
        "Burnley Room",
        "Cantilever Staircase",
        "Chapel",
        "Collectors Room",
        "Craft Museum",
        "Dec Arts Room",
        "Family Dining Room",
        "Great Hall",
        "Green Drawing Room",
        "Housekeepers Room",
        "Jacobean Staircase",
        "Kitchen",
        "Long Gallery",
        "Long Gallery Bedroom III",
        "Long Gallery Bedroom IV",
        "Long Gallery Bedroom V",
        "Long Gallery Bedroom VI",
        "Massey Gallery",
        "Military Room",
        "Natural History Gallery",
        "North Gallery",
        "North Tower (ground floor)",
        "Red Drawing Room",
        "Servants Hall",
        "Service Passage",
        "Shop Passage",
        "South Tower Bedroom",
        "Towneley Room",
        "Welcome Display",
        "on loan",
        "store"
      ],
      "$terms_acquisition_method": [
        "gift",
        "bequest",
        "purchase",
        "transfer",
        "untraced find"
      ],
      "$terms_FUAN.simple_name": [
        "accordion",
        "altarpiece",
        "armchair",
        "barrel stand",
        "barometer",
        "bed",
        "bed warmer",
        "bellows",
        "bench",
        "box",
        "cabinet",
        "candlestick",
        "case",
        "chair",
        "chandelier",
        "chest",
        "chest of drawers",
        "chiffonier",
        "clock",
        "coffer",
        "cot",
        "cradle",
        "cupboard",
        "desk",
        "dresser",
        "fire-dog",
        "font",
        "gramophone",
        "harp",
        "lectern",
        "mirror",
        "music box",
        "music stand",
        "musical instrument",
        "piano",
        "plate rack",
        "plate warmer",
        "screen",
        "sedan chair",
        "settle",
        "stool",
        "table",
        "torchere",
        "treen",
        "whatnot"
      ],
      "$terms_condition": [
        "poor",
        "fair",
        "good",
        "excellent"
      ],
      "$terms_disposal_method": [
        "transferred",
        " destroyed"
      ]
    }
  },
  "name": "Term list",
  "$props": [
    "$terms_normal_location",
    "$terms_current_location",
    "$terms_acquisition_method",
    "$terms_condition",
    "$terms_disposal_method",
    "$terms_FUAN.simple_name"
  ],
  "$groups": [
    "$identity",
    "$description",
    "$location",
    "$production",
    "$acquisition",
    "$other_info"
  ],
  "$identity": [],
  "$description": [],
  "$location": [],
  "$production": [],
  "$acquisition": [],
  "$other_info": [
    "$terms_normal_location",
    "$terms_current_location",
    "$terms_acquisition_method",
    "$terms_condition",
    "$terms_disposal_method",
    "$terms_FUAN.simple_name"
  ]
};